services:
  app:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    environment:
      - APP_ENV=${APP_ENV}
    container_name: digdir-chunker-app
    restart: unless-stopped
    user: www-data
    volumes:
      - ./:/var/www/html
    networks:
      - default
  nginx:
     image: jkaninda/nginx-fpm:alpine
     container_name: digdir-chunker-nginx-server
     restart: unless-stopped
     ports:
      - 80:80
     volumes:
      - ./:/var/www/html
     environment:
       - DOCUMENT_ROOT=/var/www/html/public
       - CLIENT_MAX_BODY_SIZE=1024M
       - PHP_FPM_HOST=app:9000
     networks:
      - default
  mariadb:
    container_name: digdir-chunker-mariadb
    env_file:
      - .env
    image: mariadb:11.7
    restart: unless-stopped
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - .docker/db/init:/docker-entrypoint-initdb.d
      - 'mariadb:/var/lib/mysql'
  meilisearch:
    image: 'getmeili/meilisearch:v1.15.1'
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: '${MEILISEARCH_MASTER_KEY}'
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    volumes:
      - 'meilisearch:/meili_data'
    networks:
      - default
    healthcheck:
      test: set -o pipefail;curl -fsS http://localhost:7700/health | grep -q '{"status":"available"}'
      retries: 3
      timeout: 5s
volumes:
  mariadb:
    driver: local
  meilisearch:
    driver: local