services:
  app:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    environment:
      - APP_ENV=${APP_ENV}
    container_name: digdir-chunker-app
    restart: unless-stopped
    user: www-data
    volumes:
      - ./:/var/www/html
    networks:
      - default
  nginx:
     image: jkaninda/nginx-fpm:alpine
     container_name: digdir-chunker-nginx-server
     restart: unless-stopped
     ports:
      - 80:80
     volumes:
      - ./:/var/www/html
     environment:
       - DOCUMENT_ROOT=/var/www/html/public
       - CLIENT_MAX_BODY_SIZE=1024M
       - PHP_FPM_HOST=app:9000
     networks:
      - default
  mariadb:
    container_name: digdir-chunker-mariadb
    env_file:
      - .env
    image: mariadb:11.8
    restart: unless-stopped
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - .docker/db/init:/docker-entrypoint-initdb.d
      - 'mariadb:/var/lib/mysql'
  minio:
    container_name: digdir-chunker-minio
    env_file:
      - .env
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - '${FORWARD_MINIO_PORT:-9000}:9000'
      - '${FORWARD_MINIO_CONSOLE_PORT:-9001}:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - 'minio:/data'
    command: server /data --console-address ":9001"
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  meilisearch:
    image: 'getmeili/meilisearch:v1.15.1'
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: '${MEILISEARCH_MASTER_KEY}'
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    volumes:
      - 'meilisearch:/meili_data'
    networks:
      - default
    healthcheck:
      test: set -o pipefail;curl -fsS http://localhost:7700/health | grep -q '{"status":"available"}'
      retries: 3
      timeout: 5s
  ollama:
    container_name: digdir-chunker-ollama
    build:
      context: .
      dockerfile: ./.docker/ollama/Dockerfile
    image: ollama/ollama:latest
    ports:
      - '${FORWARD_OLLAMA_PORT:-11434}:11434'
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
volumes:
  mariadb:
    driver: local
  minio:
    driver: local
  meilisearch:
    driver: local
  ollama:
    driver: local