services:
  app:
    image: jkaninda/laravel-php-fpm:latest
    container_name: digdir-chunker-app
    restart: unless-stopped
    user: www-data # For production
    volumes:
      - ./:/var/www/html
    networks:
      - default
  nginx:
     image: jkaninda/nginx-fpm:alpine
     container_name: digdir-chunker-nginx-server
     restart: unless-stopped
     ports:
      - 80:80
     volumes:
      - ./:/var/www/html
     environment:
       - DOCUMENT_ROOT=/var/www/html/public
       - CLIENT_MAX_BODY_SIZE=1024M
       - PHP_FPM_HOST=app:9000
        
     networks:
      - default
  mariadb:
    container_name: digdir-chunker-mariadb
    env_file:
      - .env
    image: mariadb:11.7
    restart: unless-stopped
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - .docker/db/init:/docker-entrypoint-initdb.d
      - 'mariadb:/var/lib/mysql'

volumes:
  mariadb:
    driver: local